version: '3.7'

networks:
  app_network:
    ipam:
      config:
        - subnet: 172.28.0.0/16

services:
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    networks:
      - app_network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
      - "443:443"

  traefik_abc:
    image: traefik:v2.5
    container_name: traefik_abc
    networks:
      app_network:
        ipv4_address: 172.28.1.2
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.abc_resolver.acme.email=user1@abc.com"
      - "--certificatesresolvers.abc_resolver.acme.storage=/letsencrypt/abc/acme.json"
      - "--certificatesresolvers.abc_resolver.acme.tlschallenge=true"
      - "--certificatesresolvers.abc_resolver.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory"
    labels:
      - "traefik.http.routers.traefik_abc.rule=Host(`abc.com`)"
      - "traefik.http.routers.traefik_abc.service=app_abc"
      - "traefik.http.routers.traefik_abc.tls=true"
      - "traefik.http.routers.traefik_abc.tls.certresolver=abc_resolver"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./letsencrypt:/letsencrypt"

  traefik_efg:
    image: traefik:v2.5
    container_name: traefik_efg
    networks:
      app_network:
        ipv4_address: 172.28.1.3
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.efg_resolver.acme.email=user2@efg.com"
      - "--certificatesresolvers.efg_resolver.acme.storage=/letsencrypt/efg/acme.json"
      - "--certificatesresolvers.efg_resolver.acme.tlschallenge=true"
      - "--certificatesresolvers.efg_resolver.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory"
    labels:
      - "traefik.http.routers.traefik_efg.rule=Host(`efg.com`)"
      - "traefik.http.routers.traefik_efg.service=app_efg"
      - "traefik.http.routers.traefik_efg.tls=true"
      - "traefik.http.routers.traefik_efg.tls.certresolver=efg_resolver"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./letsencrypt:/letsencrypt"

  app_abc:
    image: traefik/whoami:latest
    container_name: app_abc
    networks:
      - app_network
    command: 
      - "--port=8081"
      - "--name=abc"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.app_abc.loadbalancer.server.port=8081"
      - "traefik.http.routers.app_abc.rule=Host(`abc.com`)"
      - "traefik.http.routers.app_abc.entrypoints=websecure"
      - "traefik.http.routers.app_abc.tls=true"
      - "traefik.http.routers.app_abc.tls.certresolver=abc_resolver"
      - "traefik.http.routers.app_abc_http.rule=Host(`abc.com`)"
      - "traefik.http.routers.app_abc_http.entrypoints=web"

  app_efg:
    image: traefik/whoami:latest
    container_name: app_efg
    networks:
      - app_network
    command: 
      - "--port=8082"
      - "--name=efg"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.app_efg.loadbalancer.server.port=8082"
      - "traefik.http.routers.app_efg.rule=Host(`efg.com`)"
      - "traefik.http.routers.app_efg.entrypoints=web,websecure"
      - "traefik.http.routers.app_efg.tls=true"
      - "traefik.http.routers.app_efg.tls.certresolver=efg_resolver"
      - "traefik.http.routers.app_efg_http.rule=Host(`efg.com`)"
      - "traefik.http.routers.app_efg_http.entrypoints=web"
      
